### ISSUE TITLE
SequentialLogStore should be asynchronous

### ISSUE THREAD

**Issue by stepancheg** [andy-yx-chen/jraft#5]
Currently all `SequentialLogStore` methods are synchronous.

I need to run like 1000 state machines, and logs are persisted to database with asynchronous API. Syncrhonous `SequentialLogStore` would require 1000 threads to run this implementation.

(Probably, the problem is not only with `SequentialLogStore`).

**Comment by andy-yx-chen** [comment]
Several things, 
1. as its name indicated, the log store must be sequential (actually, the other solution is to have a B-tree index, by index number,  with non actual sequential storage), so locking is inevitable, one thing I am going to improve is to have a read/write lock instead of synchronized methods, so the implementations doesn't need to care about locking.
2. For raft implementation locking, again, the state for Raft is very important, I had a loose locking implementation before, and it turned out to be too buggy, then I decided to gave up, as a cornerstone of a distributed system, we don't want it to be unstable. To be more specific, in Raft's TLA+ spec, the correctness proven is based on messages are not processed parallel, there might be something that we can improved, but before we have a formal math spec and prove it's correct, we will not put us into that risky state, as, again, this is suppose to be the core alg of a distributed system.
3. come to your scenario, in what scenario that you need 1000 state machines to be run on the same server? even same process? and I also don't understand why 1000 instances of state machines would share the same log store? I would suggest you to scare out your application, say, running each state machine in a separated Raft instance, you may share the servers based on your load for each state machine.

**Comment by stepancheg** [comment]
Not sure I understood all of your comments, still trying to answer.

> To be more specific, in Raft's TLA+ spec, the correctness proven is based on messages are not processed parallel, there might be something that we can improved, but before we have a formal math spec and prove it's correct, we will not put us into that risky state, as, again, this is suppose to be the core alg of a distributed system.

Having CompletableFuture in return type does not imply state machine is executed in parallel. Raft engine can do nothing (not holding any thread) until CompletableFuture completes.

CompletableFuture is to execute _different_ machines in parallel.

> come to your scenario, in what scenario that you need 1000 state machines to be run on the same server? even same process?

No, it is more like 3000 state machines will be distributed among 3 clusters of 8 machines each.

Each cluster has it's own local distributed database, log could be written to that local database.

Each state machine leader and follower is not bound to concrete server, and could be migrated to different server over time.

> I also don't understand why 1000 instances of state machines would share the same log store?

Log storage database is the same, but "log files" are different.

**Comment by andy-yx-chen** [comment]
Let's start from the very beginning again, so that I can see how I can help.
It looks like you are going to run 3000 storage partitions in 3 clusters (each cluster has 8 machines, however, it equals to 7 machines, as you could only have 3 machines down at the same time), is that correct?

I that case, my understanding is for each cluster, you may need to run 1000 partitions on each cluster, so you are expecting to have a single Raft instance in each cluster, while it could handle 1000 partitions, is that right?

If that's the case, then it looks like a process that hosting the Raft instance need to take care of 1000 partitions, please correct me if I am wrong.

Something is not related and not important here about `CompletableFuture`, I have that in the implementation is to do async IO (main purpose), I also have a plan to reduce the threadpools that this implementation creates, which could save more system resources

**Comment by stepancheg** [comment]
> I that case, my understanding is for each cluster, you may need to run 1000 partitions on each cluster, so you are expecting to have a single Raft instance in each cluster, while it could handle 1000 partitions, is that right?

No, I need to run 3000 cross-cluster machines. So each cluster could be turned off any time, and system continued to work.

> If that's the case, then it looks like a process that hosting the Raft instance need to take care of 1000 partitions, please correct me if I am wrong.

Something like that.

**Comment by andy-yx-chen** [comment]
I think then you should run 3000 instances of Raft on a single machine, in that case, yes, you may need NIO for log store accessing, however, that introduces a lot of work, including changes in RaftServer (concurrent in async mode). I may upgrade to that state later but I cannot guarantee when I can deliver.

However, I just did a fix that makes whole system to share the same thread pool, that avoids too many threads to be created, you can share the same thread pool across 1000 instances of Raft, but I think you may have bottleneck at Log Store's IO

**Comment by andy-yx-chen** [comment]
I have done some [improvements](https://github.com/andy-yx-chen/jraft/commit/b240c62ec00e97f129547f512dadb822ada0a327) with the log store as well as core alg, for RaftServer itself,  I will keep many of its operations as synchronized for now, as many of them are inmemory operations, should be very fast, will close this topic now
